### ISSUE TITLE
Support for automatically generating the device token.

### ISSUE THREAD

**Issue by jspenc72** [edmundpf/robinhood_yolo#1]
Full disclosure: I am the maintainer of `robinhood-observer`.

https://www.npmjs.com/package/robinhood-observer

@edmundpf I really like your cli tool but your readme instructs users to obtain a token using:

```javascript
x=document.getElementsByTagName('script');for(i of x){y=i.innerText.match(/(?<=clientId: ").[^"]+/);if(y!=null){console.log(y[0])}}
``` 

I currently use `robinhood-observer` another npm package to generate and authenticate a new Robinhood tokens when it is needed so that I can automatically renew the token when it expires. Robinhood observer also supports native Robinhood 2FA so users input their 2fa code into the command line. 

Would you be interested in adding `robinhood-observer` as a dependency for this project so that we don't have to scrape our tokens manually from the Robinhood website?

**Comment by edmundpf** [comment]
That’s a good idea, definitely have been meaning to build in 2FA. I’m gonna take a look at how that repo gets the device token before login, it’s possible it just has logic to reproduce the expected format and generates one after some quick reading, i’ll just build that in to eliminate the need for a dependency. In terms of 2FA, what i’ve noticed is different in my repo vs others is mine logs in once via a request, then saves an auth token so that it doesn’t have to keep doing login requests (the token lasts 24 hours, if user has been inactive in that time, must log in again). I could just build in a method that if 2FA is needed the script stops until prompt is answered then continues as usual.

**Comment by edmundpf** [comment]
We should talk about merging some of the features in our repos together for sure, as far as i’ve seen, other repos have just covered buying/selling equities. Between the two we have options and crypto functionality added.

**Comment by jspenc72** [comment]
You can definitely use the logic. To avoid duplication of code in happy to extract the functionality into a separate module and add you add a maintainer?

**Comment by jspenc72** [comment]
I suspect that will update every time robinhood updates their api...

**Comment by jspenc72** [comment]
Yes, it just has to match a given format and then you have to register the device. Using users credentials, then respond to 2fa.

**Comment by jspenc72** [comment]
On top of just authentication, Robinhood observer caches the device token and the jwt in a file called device.json by default... If that file does not exist or token is expired it updates the 2fa... It actually took a while to get it all working just right. It also pulls username and password from process.env for 12 factor app compliance and it's much  easier use with kubernetes and docker...

**Comment by jspenc72** [comment]
I had options on my road map but when your project popped up it became less of a priority.

**Comment by edmundpf** [comment]
Nice. That's a solid setup, how'd you figure out the device token format the API expected? I saw your code and you're just generating one.

**Comment by jspenc72** [comment]
You can contact me through: 
http://jspenc.software 
If you want to discuss details.
